### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by Lawliet247** [DavePearcey/ValkyriesFall-Public#11]
I register with my email, and wont barge from the option,, then I try to register again, they said "Email address already in use." then I try Login, I can't. how can I proceed now? need advice

**Comment by DavePearcey** [comment]
Do you get a form validation error when you login, maybe the username or password was typed in incorrectly?

what was the username? if you can't get in, I can alwaysmanually reset the password and email it to the email you signed up with?

**Comment by Lawliet247** [comment]
Loknarg or Loser247,I dont remember what I use first time I register was Loknarg, after I click Register, nothing happened, then I try to Register again, "Email address already in use."..

**Comment by DavePearcey** [comment]
I see the account. It looks like, the timing of your account creating may have been unlucky. there's a daily cleanup script that happens at midnight server time and your sign up matches the timing perfectly. It may have caused a timeout in the creation of your character and not finished setting it up correctly.

I've reset the accounts password. I'll email it to the address associated with the account after this comment.

**Comment by DavePearcey** [comment]
I have found the issue in code. There was differences in code and config when it came to password validation. Code required a minimum of 8 characters, but the configuration for the password validator required 10. So those with passwords 8 or 9 characters long would get an error when validating their login. This will be released as a hot fix today.
