### ISSUE TITLE
"Server Error in '/' Application. Runtime Error" when logging in.

### ISSUE THREAD

**Issue by egeren** [DavePearcey/ValkyriesFall-Public#16]
When i click login i'm getting an error.
I think there is some bug on back-end.

![bug](https://user-images.githubusercontent.com/32365178/81035570-30a32380-8ea4-11ea-9d11-a48b69b04b6c.png)

btw my username is "Pumpkin Duke" if it's necessary

**Comment by DavePearcey** [comment]
I have found the issue in code. There was differences in code and config when it came to password validation. Code required a minimum of 8 characters, but the configuration for the password validator required 10. So those with passwords 8 or 9 characters long would get an error when validating their login. This will be released as a hot fix today.
